# Generated by Django on 2026-04-20

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create schema
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS audit;',
            reverse_sql='DROP SCHEMA IF EXISTS audit CASCADE;'
        ),
        # Create AuditLog model
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('INSERT', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('EXPORT', 'Exportar')], max_length=20)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.UUIDField(blank=True, help_text='ID de sesión de auth', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
        # Create AccessLog model
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Logs de Acceso',
                'db_table': 'access_logs',
                'ordering': ['-created_at'],
            },
        ),
        # Create Export model
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportación',
                'verbose_name_plural': 'Exportaciones',
                'db_table': 'exports',
                'ordering': ['-created_at'],
            },
        ),
        # Create indexes
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON logs(user_id);
            CREATE INDEX IF NOT EXISTS idx_audit_logs_table_record ON logs(table_name, record_id);
            CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON logs(created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_audit_access_logs_user_id ON access_logs(user_id);
            CREATE INDEX IF NOT EXISTS idx_audit_access_logs_created_at ON access_logs(created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_audit_exports_user_id ON exports(user_id);
            CREATE INDEX IF NOT EXISTS idx_audit_exports_created_at ON exports(created_at DESC);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_audit_logs_user_id;
            DROP INDEX IF EXISTS idx_audit_logs_table_record;
            DROP INDEX IF EXISTS idx_audit_logs_created_at;
            DROP INDEX IF EXISTS idx_audit_access_logs_user_id;
            DROP INDEX IF EXISTS idx_audit_access_logs_created_at;
            DROP INDEX IF EXISTS idx_audit_exports_user_id;
            DROP INDEX IF EXISTS idx_audit_exports_created_at;
            """
        ),
    ]