# Generated by Django 6.0.4 on 2026-04-22 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user'], name='access_logs_user_id_4502b2_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['-created_at'], name='access_logs_created_3954b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='logs_user_id_1f4728_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name', 'record_id'], name='logs_table_n_b2cae3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='logs_created_dfc914_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['user'], name='exports_user_id_f1afa9_idx'),
        ),
        migrations.AddIndex(
            model_name='export',
            index=models.Index(fields=['-created_at'], name='exports_created_ad41ea_idx'),
        ),
    ]
