# Generated by Django 6.0.4 on 2026-04-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_export_error_message_export_status_export_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device_info',
            field=models.JSONField(blank=True, help_text='Detalles del navegador y OS', null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
