# Generated by Django on 2026-04-20

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create schema
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS ats;',
            reverse_sql='DROP SCHEMA IF EXISTS ats CASCADE;'
        ),
        # Create Form model
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'db_table': 'forms',
                'ordering': ['-created_at'],
            },
        ),
        # Create Job model
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Tiempo Completo'), ('part-time', 'Medio Tiempo'), ('contract', 'Contrato'), ('remote', 'Remoto')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierta'), ('closed', 'Cerrada')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ats.form')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        # Create Candidate model
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(choices=[('applied', 'Aplicados'), ('screening', 'Screening'), ('interview', 'Entrevista'), ('offer', 'Oferta'), ('hired', 'Contratado'), ('rejected', 'Rechazado')], default='applied', max_length=20)),
                ('resume_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ats.job')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidates',
                'ordering': ['-applied_at'],
            },
        ),
        # Create CandidateDocument model
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('doc_type', models.CharField(choices=[('cv', 'Currículum'), ('portfolio', 'Portafolio'), ('certificate', 'Certificado'), ('id', 'Identificación'), ('other', 'Otro')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ats.candidate')),
            ],
            options={
                'verbose_name': 'Documento de Candidato',
                'verbose_name_plural': 'Documentos de Candidatos',
                'db_table': 'candidate_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        # Create Activity model
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('stage_change', 'Cambio de Etapa'), ('note', 'Nota'), ('message', 'Mensaje'), ('rating_change', 'Cambio de Calificación'), ('application', 'Aplicación'), ('form_submission', 'Envío de Formulario')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ats.candidate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        # Create Message model
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('template', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ats.candidate')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'messages',
                'ordering': ['-sent_at'],
            },
        ),

        # Create FormField model
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('help_text', models.TextField(blank=True)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('conditional_rules', models.JSONField(blank=True, default=list)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ats.form')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formularios',
                'db_table': 'form_fields',
                'ordering': ['field_order'],
            },
        ),
        # Create FormChain model
        migrations.CreateModel(
            name='FormChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_form', models.ForeignKey(help_text='Formulario que redirige a otro', on_delete=django.db.models.deletion.CASCADE, related_name='chained_forms', to='ats.form')),
                ('to_form', models.ForeignKey(help_text='Formulario destino', on_delete=django.db.models.deletion.CASCADE, related_name='chained_from', to='ats.form')),
            ],
            options={
                'verbose_name': 'Cadena de Formularios',
                'verbose_name_plural': 'Cadenas de Formularios',
                'db_table': 'form_chains',
                'unique_together': {('from_form', 'to_form')},
            },
        ),
        # Create SentForm model
        migrations.CreateModel(
            name='SentForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('expired', 'Expirado')], default='pending', max_length=10)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_forms', to='ats.candidate')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_forms', to='ats.form')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_forms', to='ats.job')),
            ],
            options={
                'verbose_name': 'Formulario Enviado',
                'verbose_name_plural': 'Formularios Enviados',
                'db_table': 'sent_forms',
                'ordering': ['-sent_at'],
            },
        ),
        # Create FormSubmission model
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('file_data', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='ats.candidate')),
                ('chained_from_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chained_submissions', to='ats.form')),
                ('chained_from_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chained_responses', to='ats.formsubmission')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ats.form')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='ats.job')),
            ],
            options={
                'verbose_name': 'Respuesta de Formulario',
                'verbose_name_plural': 'Respuestas de Formularios',
                'db_table': 'form_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        # Create JobAssignment model
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ats.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Vacante',
                'verbose_name_plural': 'Asignaciones de Vacantes',
                'db_table': 'job_assignments',
                'unique_together': {('job', 'user')},
            },
        ),
        # Create indexes
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
            CREATE INDEX IF NOT EXISTS idx_jobs_department ON jobs(department);
            CREATE INDEX IF NOT EXISTS idx_jobs_created_by_id ON jobs(created_by_id);
            CREATE INDEX IF NOT EXISTS idx_candidates_job_id ON candidates(job_id);
            CREATE INDEX IF NOT EXISTS idx_candidates_stage ON candidates(stage);
            CREATE INDEX IF NOT EXISTS idx_candidates_email ON candidates(email);
            CREATE INDEX IF NOT EXISTS idx_activities_candidate_id ON activities(candidate_id);
            CREATE INDEX IF NOT EXISTS idx_activities_type ON activities(type);
            CREATE INDEX IF NOT EXISTS idx_activities_created_at ON activities(created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_messages_candidate_id ON messages(candidate_id);
            CREATE INDEX IF NOT EXISTS idx_messages_sent_at ON messages(sent_at DESC);
            CREATE INDEX IF NOT EXISTS idx_forms_is_template ON forms(is_template);
            CREATE INDEX IF NOT EXISTS idx_form_fields_form_id ON form_fields(form_id);
            CREATE INDEX IF NOT EXISTS idx_sent_forms_token ON sent_forms(token);
            CREATE INDEX IF NOT EXISTS idx_sent_forms_candidate_id ON sent_forms(candidate_id);
            CREATE INDEX IF NOT EXISTS idx_sent_forms_status ON sent_forms(status);
            CREATE INDEX IF NOT EXISTS idx_form_submissions_candidate_id ON form_submissions(candidate_id);
            CREATE INDEX IF NOT EXISTS idx_form_submissions_form_id ON form_submissions(form_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_jobs_status;
            DROP INDEX IF EXISTS idx_jobs_department;
            DROP INDEX IF EXISTS idx_jobs_created_by;
            DROP INDEX IF EXISTS idx_candidates_job_id;
            DROP INDEX IF EXISTS idx_candidates_stage;
            DROP INDEX IF EXISTS idx_candidates_email;
            DROP INDEX IF EXISTS idx_activities_candidate_id;
            DROP INDEX IF EXISTS idx_activities_type;
            DROP INDEX IF EXISTS idx_activities_created_at;
            DROP INDEX IF EXISTS idx_messages_candidate_id;
            DROP INDEX IF EXISTS idx_messages_sent_at;
            DROP INDEX IF EXISTS idx_forms_is_template;
            DROP INDEX IF EXISTS idx_form_fields_form_id;
            DROP INDEX IF EXISTS idx_sent_forms_token;
            DROP INDEX IF EXISTS idx_sent_forms_candidate_id;
            DROP INDEX IF EXISTS idx_sent_forms_status;
            DROP INDEX IF EXISTS idx_form_submissions_candidate_id;
            DROP INDEX IF EXISTS idx_form_submissions_form_id;
            """
        ),
    ]