# Generated by Django 6.0.4 on 2026-04-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('expirado', 'Expirado')], default='pending', max_length=10),
        ),
    ]
