# Generated by Django 6.0.4 on 2026-04-28 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBucket',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('owner', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('avif_autodetection', models.BooleanField(default=False)),
                ('file_size_limit', models.BigIntegerField(blank=True, null=True)),
                ('allowed_mime_types', models.TextField(blank=True, null=True)),
                ('owner_id', models.TextField(blank=True, null=True)),
                ('type', models.TextField(default='STANDARD')),
            ],
            options={
                'verbose_name': 'Storage Bucket',
                'verbose_name_plural': 'Storage Buckets',
                'db_table': '"storage"."buckets"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_id', models.TextField()),
                ('name', models.TextField()),
                ('owner', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.TextField(blank=True, null=True)),
                ('owner_id', models.TextField(blank=True, null=True)),
                ('user_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Storage Object',
                'verbose_name_plural': 'Storage Objects',
                'db_table': '"storage"."objects"',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsyncUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.TextField()),
                ('bucket_id', models.TextField(default='user-files')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('temp_redis_key', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'async_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
