# Generated by Django 6.0.4 on 2026-05-05 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ats_roles', '0004_module_is_system_permission_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ID técnico (ej: vehiculos)', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Nombre visible (ej: Vehículos)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_schema', to='ats_roles.module')),
            ],
            options={
                'verbose_name': 'Definición de Entidad',
                'verbose_name_plural': 'Definiciones de Entidades',
                'db_table': 'dynamic_entity_definitions',
            },
        ),
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='Datos reales del registro en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='dynamic_entities.entitydefinition')),
            ],
            options={
                'verbose_name': 'Dato Dinámico',
                'verbose_name_plural': 'Datos Dinámicos',
                'db_table': 'dynamic_data_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ID técnico del campo (ej: placa)', max_length=50)),
                ('label', models.CharField(help_text='Nombre visible del campo (ej: Placa)', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano'), ('select', 'Selección'), ('textarea', 'Área de Texto')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, help_text="Opciones para campos tipo 'select' [v1, v2]", null=True)),
                ('order', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dynamic_entities.entitydefinition')),
            ],
            options={
                'verbose_name': 'Definición de Campo',
                'verbose_name_plural': 'Definiciones de Campos',
                'db_table': 'dynamic_field_definitions',
                'ordering': ['order'],
                'unique_together': {('entity', 'name')},
            },
        ),
    ]
