# Generated by Django on 2026-04-20

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create schema
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS ats_roles;',
            reverse_sql='DROP SCHEMA IF EXISTS ats_roles CASCADE;'
        ),
        # Create Permission model
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, unique=True, choices=[('job:create', 'Crear vacantes'), ('job:read', 'Ver vacantes'), ('job:update', 'Editar vacantes'), ('job:delete', 'Eliminar vacantes'), ('job:assign_recruiter', 'Asignar responsables a vacantes'), ('candidate:create', 'Crear candidatos'), ('candidate:read', 'Ver candidatos'), ('candidate:update', 'Editar candidatos'), ('candidate:delete', 'Eliminar candidatos'), ('candidate:move_stage', 'Mover entre etapas del pipeline'), ('activity:create', 'Crear actividades'), ('activity:read', 'Ver actividades'), ('activity:delete', 'Eliminar actividades'), ('message:send', 'Enviar mensajes'), ('message:read', 'Ver mensajes'), ('message:delete', 'Eliminar mensajes'), ('form:create', 'Crear formularios'), ('form:read', 'Ver formularios'), ('form:update', 'Editar formularios'), ('form:delete', 'Eliminar formularios'), ('form:assign', 'Asignar formularios a vacantes'), ('submission:read', 'Ver envíos de formularios'), ('submission:review', 'Revisar envíos'), ('submission:approve', 'Aprobar/rechazar envíos'), ('analytics:read', 'Ver analytics'), ('analytics:export', 'Exportar reportes'), ('user:invite', 'Invitar usuarios'), ('user:manage_roles', 'Gestionar roles de usuarios'), ('settings:manage', 'Gestionar configuración del sistema')])),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('jobs', 'Vacantes'), ('candidates', 'Candidatos'), ('activities', 'Actividades'), ('messages', 'Mensajes'), ('forms', 'Formularios'), ('submissions', 'Envíos'), ('analytics', 'Analytics'), ('users', 'Usuarios'), ('settings', 'Configuración')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permissions',
            },
        ),
        # Create Role model
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        # Create RolePermission model
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='ats_roles.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='ats_roles.role')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        # Create UserRole model
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='ats_roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
        # Create UserResourcePermission model
        migrations.CreateModel(
            name='UserResourcePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('job', 'Vacante'), ('department', 'Departamento')], max_length=20)),
                ('resource_id', models.UUIDField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resource_permissions', to='ats_roles.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Recurso',
                'verbose_name_plural': 'Permisos de Recursos',
                'db_table': 'user_resource_permissions',
                'unique_together': {('user', 'permission', 'resource_type', 'resource_id')},
            },
        ),
        # Insert initial data - Permissions
        migrations.RunSQL(
            sql="""
            INSERT INTO permissions (id, action, description, category, created_at) VALUES
            (gen_random_uuid(), 'job:create', 'Crear vacantes', 'jobs', NOW()),
            (gen_random_uuid(), 'job:read', 'Ver vacantes', 'jobs', NOW()),
            (gen_random_uuid(), 'job:update', 'Editar vacantes', 'jobs', NOW()),
            (gen_random_uuid(), 'job:delete', 'Eliminar vacantes', 'jobs', NOW()),
            (gen_random_uuid(), 'job:assign_recruiter', 'Asignar responsables a vacantes', 'jobs', NOW()),
            (gen_random_uuid(), 'candidate:create', 'Crear candidatos', 'candidates', NOW()),
            (gen_random_uuid(), 'candidate:read', 'Ver candidatos', 'candidates', NOW()),
            (gen_random_uuid(), 'candidate:update', 'Editar candidatos', 'candidates', NOW()),
            (gen_random_uuid(), 'candidate:delete', 'Eliminar candidatos', 'candidates', NOW()),
            (gen_random_uuid(), 'candidate:move_stage', 'Mover entre etapas del pipeline', 'candidates', NOW()),
            (gen_random_uuid(), 'activity:create', 'Crear actividades', 'activities', NOW()),
            (gen_random_uuid(), 'activity:read', 'Ver actividades', 'activities', NOW()),
            (gen_random_uuid(), 'activity:delete', 'Eliminar actividades', 'activities', NOW()),
            (gen_random_uuid(), 'message:send', 'Enviar mensajes', 'messages', NOW()),
            (gen_random_uuid(), 'message:read', 'Ver mensajes', 'messages', NOW()),
            (gen_random_uuid(), 'message:delete', 'Eliminar mensajes', 'messages', NOW()),
            (gen_random_uuid(), 'form:create', 'Crear formularios', 'forms', NOW()),
            (gen_random_uuid(), 'form:read', 'Ver formularios', 'forms', NOW()),
            (gen_random_uuid(), 'form:update', 'Editar formularios', 'forms', NOW()),
            (gen_random_uuid(), 'form:delete', 'Eliminar formularios', 'forms', NOW()),
            (gen_random_uuid(), 'form:assign', 'Asignar formularios a vacantes', 'forms', NOW()),
            (gen_random_uuid(), 'submission:read', 'Ver envíos de formularios', 'submissions', NOW()),
            (gen_random_uuid(), 'submission:review', 'Revisar envíos', 'submissions', NOW()),
            (gen_random_uuid(), 'submission:approve', 'Aprobar/rechazar envíos', 'submissions', NOW()),
            (gen_random_uuid(), 'analytics:read', 'Ver analytics', 'analytics', NOW()),
            (gen_random_uuid(), 'analytics:export', 'Exportar reportes', 'analytics', NOW()),
            (gen_random_uuid(), 'user:invite', 'Invitar usuarios', 'users', NOW()),
            (gen_random_uuid(), 'user:manage_roles', 'Gestionar roles de usuarios', 'users', NOW()),
            (gen_random_uuid(), 'settings:manage', 'Gestionar configuración del sistema', 'settings', NOW());
            """,
            reverse_sql='DELETE FROM permissions;'
        ),
        # Insert initial data - Roles
        migrations.RunSQL(
            sql="""
            INSERT INTO roles (id, name, description, is_system, created_at, updated_at) VALUES
            (gen_random_uuid(), 'super_admin', 'Administrador total del sistema', true, NOW(), NOW()),
            (gen_random_uuid(), 'recruiter_manager', 'Gestor de reclutamiento', true, NOW(), NOW()),
            (gen_random_uuid(), 'recruiter', 'Reclutador', true, NOW(), NOW()),
            (gen_random_uuid(), 'viewer', 'Solo lectura', true, NOW(), NOW());
            """,
            reverse_sql='DELETE FROM roles;'
        ),
        # Insert role permissions - super_admin (all permissions)
        migrations.RunSQL(
            sql="""
            INSERT INTO role_permissions (role_id, permission_id, granted_at)
            SELECT 
                (SELECT id FROM roles WHERE name = 'super_admin'),
                id,
                NOW()
            FROM permissions;
            """,
            reverse_sql='DELETE FROM role_permissions;'
        ),
        # Insert role permissions - recruiter_manager
        migrations.RunSQL(
            sql="""
            INSERT INTO role_permissions (role_id, permission_id, granted_at)
            SELECT 
                (SELECT id FROM roles WHERE name = 'recruiter_manager'),
                id,
                NOW()
            FROM permissions
            WHERE action NOT IN ('user:manage_roles', 'settings:manage');
            """,
            reverse_sql='DELETE FROM role_permissions;'
        ),
        # Insert role permissions - recruiter
        migrations.RunSQL(
            sql="""
            INSERT INTO role_permissions (role_id, permission_id, granted_at)
            SELECT 
                (SELECT id FROM roles WHERE name = 'recruiter'),
                id,
                NOW()
            FROM permissions
            WHERE action IN (
                'job:read', 'job:update',
                'candidate:create', 'candidate:read', 'candidate:update', 'candidate:move_stage',
                'activity:create', 'activity:read',
                'message:send', 'message:read',
                'form:read', 'form:assign',
                'submission:read', 'submission:review',
                'analytics:read'
            );
            """,
            reverse_sql='DELETE FROM role_permissions;'
        ),
        # Insert role permissions - viewer
        migrations.RunSQL(
            sql="""
            INSERT INTO role_permissions (role_id, permission_id, granted_at)
            SELECT 
                (SELECT id FROM roles WHERE name = 'viewer'),
                id,
                NOW()
            FROM permissions
            WHERE action IN (
                'job:read',
                'candidate:read',
                'activity:read',
                'message:read',
                'form:read',
                'submission:read',
                'analytics:read', 'analytics:export'
            );
            """,
            reverse_sql='DELETE FROM role_permissions;'
        ),
    ]