# Generated by Django 6.0.4 on 2026-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(help_text='Identificador único de la acción (ej: job:create)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(blank=True, help_text='Categoría lógica (ej: jobs, users)', max_length=50),
        ),
    ]
