# Generated by Django 6.0.4 on 2026-05-04 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_roles', '0002_alter_permission_action_alter_permission_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ID interno del módulo (ej: dashboard)', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Nombre visible en el menú', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono (ej: Briefcase)', max_length=50)),
                ('route', models.CharField(blank=True, help_text='Ruta de navegación (ej: /dashboard/vacantes)', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='ats_roles.module'),
        ),
    ]
