# Generated by Django 6.0.4 on 2026-05-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_roles', '0003_module_permission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
