# Generated by Django 6.0.4 on 2026-04-10 23:20
# Updated: removed PermissionsMixin fields (groups, user_permissions)
# User is managed=False — Supabase owns auth.users

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS auth;',
            reverse_sql='DROP SCHEMA IF EXISTS auth CASCADE;'
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='encrypted_password', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_sign_in_at', null=True)),
                ('is_superuser', models.BooleanField(db_column='is_super_admin', default=False)),
                ('raw_app_meta_data', models.JSONField(blank=True, default=dict)),
                ('raw_user_meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': '"auth"."users"',
                'managed': False,
            },
        ),
    ]

