# Generated by Django 6.0.4 on 2026-04-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField()),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_login_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_login__user_id_b7d13a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_jti', models.CharField(max_length=255, unique=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'), models.Index(fields=['user', '-created_at'], name='user_sessio_user_id_35bce9_idx')],
            },
        ),
    ]
